name: xcodeproj
description: A library for reading and modifying XCode projects.
version: 0.1.0-dev.2
homepage: https://github.com/appsup-dart/xcodeproj

environment:
  sdk: '>=2.8.1 <3.0.0'
  

dependencies:
  petitparser: ^3.1.0
  xml: ^4.5.1
  snapshot: ^0.1.0-dev.3
  pointycastle: ^1.0.0
  path: ^1.7.0
  quiver: ^2.1.3

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
